tasks:
  # Task to install general utilities
  - name: utils
    before: |
      sudo apt update
      sudo apt-get install -y tree

  # Task to install AWS CLI
  # Reference: https://docs.aws.amazon.com/cli/latest/userguide/getting-started-install.html
  - name: aws-cli
    env: 
      AWS_CLI_AUTO_PROMPT: on-partial
      AWS_DEFAULT_REGION: ap-south-1
    before: |
      cd /workspace
      curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
      unzip awscliv2.zip
      sudo ./aws/install
      cd $THEIA_WORKSPACE_ROOT
    init: |
      gp env AWS_DEFAULT_REGION=ap-south-1

  # Task to install Terraform CLI
  # Reference: https://developer.hashicorp.com/terraform/tutorials/aws-get-started/install-cli
  - name: terraform-cli
    before: |
      chmod u+x /workspace/AWS-SAA-PREP/s3/iac/terraform/terraform_cli
      ./terraform_cli
