#!/usr/bin/env bash

echo "== deploy ec2 with security group in a vpc via CFN"

STACK_NAME="cfn-ec2-sgs"

aws cloudformation deploy \
--template-file template.yml \
--capabilities CAPABILITY_IAM \
--region ap-south-1 \
--stack-name $STACK_NAME
